### ISSUE TITLE
bug: Too much runners exported

### ISSUE THREAD

**Issue by PaulLesur** [tchelovilar/github-org-runner-exporter#12]
I spawned a pool of 20 runners with the same label, and started a Github Action Workflow that uses these runners.
I noticed on my Grafana Dashboard that the data are incoherent : 
![image](https://user-images.githubusercontent.com/11136367/140304234-dc4ddaa3-ddba-4d99-bd20-a45033d40eaa.png)
In fact the busy runners are correct, but there are runners with busy=false that remain in the metrics whereas it is not true. I have a total of 31 runners where I should only have 20. :thinking: 
![bitmap](https://user-images.githubusercontent.com/11136367/140305245-e8be0aaa-b85e-4d91-89df-1bd3f7ebda97.png)

**Comment by tchelovilar** [comment]
Hi Paul,

Do you have offline runners? Check on GitHub settings page, the actions section, maybe there's some offline runners there.

Also there is an dashboard template available on this repository, test it.

**Comment by PaulLesur** [comment]
Hello, I checked the runners list on my Github org before opening the issue and there were only 20 runners.
In fact, I imported your dashboard in my Grafana instance and modified it to my custom needs :)

I will investigate the issue when I wiil have time for that and I'll keep you informed.


EDIT: OOOOh !! I just understand what you mean by "Do you have offline runners? " and yes I had offline runners in these... OK so no bug then ! Sorry for the inconvenience :sweat_smile:
