### ISSUE TITLE
Permissions Issue 

### ISSUE THREAD

**Issue by harsha-chamarthi** [tchelovilar/github-org-runner-exporter#15]
Hi,

I have created token with Read permissons to the org, but i see the below error in the logs 

ERROR:root:Api request returned error: Forbidden {"message":"Must have admin rights to Repository.","documentation_url":"https://docs.github.com/rest/reference/actions#list-self-hosted-runners-for-an-organization

Do we need any additional permissions?

**Comment by tchelovilar** [comment]
Hi,

I think it needs all permissions from admin:org

**Comment by harsha-chamarthi** [comment]
Ok, thank you
