### ISSUE TITLE
Enhancement proposal: exporting jobs metrics

### ISSUE THREAD

**Issue by goshlanguage** [tchelovilar/github-org-runner-exporter#24]
Hey @tchelovilar, 

I was curious to know what the scope of this project is?

I am looking for some functionality to also track runners in my repo, and long running jobs in my org/repo. I know the name of the project is pretty succinct, but I would love to leverage this project for these purposes if it would be a welcomed addition. 

What are your thoughts?

Thanks!

**Comment by tchelovilar** [comment]
HI @goshlanguage ,

The purpose is to have metrics about the self-hosted runners, to have alerts in case no runner is available, and also to scale the pods when all runners are busy.  

To track the job duration, maybe this project will be better for you:
https://github.com/Labbs/github-actions-exporter

Best

**Comment by goshlanguage** [comment]
Thanks for your help! I appreciate the suggestion.
