### ISSUE TITLE
Only first page of runners are returned

### ISSUE THREAD

**Issue by PaulLesur** [tchelovilar/github-org-runner-exporter#9]
I have hundreds of runners for my org but only few are exported. After seeing the source code, it seems that only the first page of runners are exported (default to 30 runners according to the Github API documentation).
It should iterate over all pages to export all runners.

I will try to do a fix. :slightly_smiling_face:

**Comment by tchelovilar** [comment]
Hi Paul,

Thank you for reporting and purpose a solution. I was thinking to do it in a different approach:

https://github.com/tchelovilar/github-org-runner-exporter/pull/11

What do you think about it?

Thanks

**Comment by PaulLesur** [comment]
Hi ! 
Your solution seems better as it returns the right ratelimit remaining requests and is cleaner than mine.
I will close my PR.

**Comment by tchelovilar** [comment]
Hi @PaulLesur,

I'm not an expert also, but again many thanks for the report and contribution.

**Comment by PaulLesur** [comment]
Thank you for this exporter, it is very useful !
